"""Attribution and Control-Plane Domain Models, Services, and Verifiers."""

from app.trading.attribution.classifier import AttributionClassifier
from app.trading.attribution.evaluator import DecisionEvaluator, ExecutionEvaluator
from app.trading.attribution.models import (
    AttributionClass,
    AttributionReport,
    DecisionArtifact,
    DecisionOutcomeRecord,
    ExecutionIntent,
    ExecutionReconciliation,
    IntentStatus,
    OrderAttempt,
    OrderAttemptStatus,
    OutcomeMaturityStatus,
    PolicyDecision,
    PolicyDisposition,
    ReconciliationVerdict,
)
from app.trading.attribution.repository import (
    consume_execution_intent,
    ensure_attribution_indexes,
    get_attribution_report,
    get_attribution_report_by_decision,
    get_decision_artifact,
    get_execution_intent,
    get_execution_intent_by_decision,
    get_policy_decision,
    get_policy_decision_by_decision,
    save_attribution_report,
    save_decision_artifact,
    save_execution_intent,
    save_execution_reconciliation,
    save_order_attempt,
    save_policy_decision,
)
from app.trading.attribution.verifier import (
    verify_cycle_lineage,
    verify_fill_lineage,
    verify_intent_lineage,
)

__all__ = [
    "AttributionClass",
    "AttributionClassifier",
    "AttributionReport",
    "DecisionArtifact",
    "DecisionEvaluator",
    "DecisionOutcomeRecord",
    "ExecutionEvaluator",
    "ExecutionIntent",
    "ExecutionReconciliation",
    "IntentStatus",
    "OrderAttempt",
    "OrderAttemptStatus",
    "OutcomeMaturityStatus",
    "PolicyDecision",
    "PolicyDisposition",
    "ReconciliationVerdict",
    "consume_execution_intent",
    "ensure_attribution_indexes",
    "get_attribution_report",
    "get_attribution_report_by_decision",
    "get_decision_artifact",
    "get_execution_intent",
    "get_execution_intent_by_decision",
    "get_policy_decision",
    "get_policy_decision_by_decision",
    "save_attribution_report",
    "save_decision_artifact",
    "save_execution_intent",
    "save_execution_reconciliation",
    "save_order_attempt",
    "save_policy_decision",
    "verify_cycle_lineage",
    "verify_fill_lineage",
    "verify_intent_lineage",
]
