"""
Integration and mock tests for lazy-tool-service tool forwarding.
Verifies that when USE_LAZY_TOOL_SERVICE=true, the ToolRegistry forwards
tool execution requests to the sidecar endpoint and processes the response.
"""

import os
import json
import pytest
from unittest.mock import patch, AsyncMock, MagicMock

# Import the registry directly
from app.tools.registry import registry


@pytest.fixture(autouse=True)
def register_test_tool():
    """Register a temporary tool for integration tests."""
    @registry.register(
        name="test_dummy_tool",
        description="A dummy tool for testing",
        parameters={
            "type": "object",
            "properties": {"val": {"type": "integer"}},
            "required": ["val"],
        },
        tier=0,
    )
    async def test_dummy_tool(val: int):
        return f"local {val}"

    yield

    # Clean up so the tool does not leak into the next test.
    #
    # This used to remove the three pieces by hand — `del registry.tools[...]`,
    # a list comprehension over `registry.schemas`, `del registry._meta[...]` —
    # which left `_schema_index` still pointing at the removed slot. The SECOND
    # test in this file then raised IndexError at fixture setup, so both have
    # been erroring since long before 2026-08-06. Worse than the crash: the
    # comprehension shifts every later schema down one, so a stale index that
    # stays in range resolves to a DIFFERENT tool and silently overwrites its
    # schema. `unregister()` (lazycat-sdk 0.3.11) moves all four together.
    registry.unregister("test_dummy_tool")


@pytest.mark.asyncio
async def test_lazy_tool_service_forwarding():
    """Test forwarding to lazy-tool-service when USE_LAZY_TOOL_SERVICE=true."""
    with patch.dict(os.environ, {
        "USE_LAZY_TOOL_SERVICE": "true",
        "LAZY_TOOL_SERVICE_URL": "http://10.0.0.16:7788",
        "LAZY_TOOL_SERVICE_PORT": "7788",
    }):
        mock_client_instance = AsyncMock()
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {"content": "sidecar-result"}
        mock_client_instance.post.return_value = mock_response

        mock_client_instance.__aenter__.return_value = mock_client_instance
        mock_client_instance.__aexit__.return_value = None

        with patch("httpx.AsyncClient", return_value=mock_client_instance):
            tool_call = {
                "id": "call_123",
                "type": "function",
                "function": {
                    "name": "test_dummy_tool",
                    "arguments": '{"val": 42}'
                }
            }
            res = await registry.execute_tool_call(tool_call)

            # Check response structure
            assert res["role"] == "tool"
            assert res["tool_call_id"] == "call_123"
            assert res["name"] == "test_dummy_tool"
            assert res["content"] == "sidecar-result"

            # Check request details
            mock_client_instance.post.assert_called_once_with(
                "http://10.0.0.16:7788/execute/test_dummy_tool",
                json={"arguments": {"val": 42}},
                headers=None
            )


@pytest.mark.asyncio
async def test_lazy_tool_service_disabled():
    """Test local execution fallback when USE_LAZY_TOOL_SERVICE=false."""
    with patch.dict(os.environ, {"USE_LAZY_TOOL_SERVICE": "false"}):
        tool_call = {
            "id": "call_456",
            "type": "function",
            "function": {
                "name": "test_dummy_tool",
                "arguments": '{"val": 100}'
            }
        }
        res = await registry.execute_tool_call(tool_call)

        # Output should be generated by local execution
        assert res["role"] == "tool"
        assert res["tool_call_id"] == "call_456"
        assert res["name"] == "test_dummy_tool"
        assert res["content"] == "local 100"


@pytest.mark.asyncio
async def test_lazy_tool_service_http_failure():
    """Test that HTTP non-200 responses are handled gracefully."""
    with patch.dict(os.environ, {
        "USE_LAZY_TOOL_SERVICE": "true",
        "LAZY_TOOL_SERVICE_URL": "http://10.0.0.16:7788",
        "LAZY_TOOL_SERVICE_PORT": "7788",
    }):
        mock_client_instance = AsyncMock()
        mock_response = MagicMock()
        mock_response.status_code = 500
        mock_response.text = "Internal Service Error"
        mock_client_instance.post.return_value = mock_response

        mock_client_instance.__aenter__.return_value = mock_client_instance
        mock_client_instance.__aexit__.return_value = None

        with patch("httpx.AsyncClient", return_value=mock_client_instance):
            tool_call = {
                "id": "call_789",
                "type": "function",
                "function": {
                    "name": "test_dummy_tool",
                    "arguments": '{"val": 42}'
                }
            }
            res = await registry.execute_tool_call(tool_call)

            # Response should capture the error
            assert res["role"] == "tool"
            assert res["tool_call_id"] == "call_789"
            assert res["name"] == "test_dummy_tool"
            
            error_data = json.loads(res["content"])
            assert "error" in error_data
            assert "lazy-tool-service returned status code 500" in error_data["error"]
