"""
Reflection Utilities — Shared functions for Autoresearch and Self-Improvement Loops.
"""


def generate_critique_prompt(base_prompt: str, critique: str, attempt: int) -> str:
    """
    Append an explicit failure critique to an agent's system prompt for the next retry iteration.

    Args:
        base_prompt: The original system prompt.
        critique: The explicit failure analysis generated by the Critic model.
        attempt: The current retry attempt number (1-indexed).

    Returns:
        The evolved system prompt containing the strict critique instructions.
    """
    if not critique:
        return base_prompt

    evolved = f"""{base_prompt}

=========================================
[AUTORESEARCH REFLECTION: ATTEMPT {attempt} FAILED]
Your previous response failed validation. 
CRITIQUE FROM EVALUATOR:
{critique}

INSTRUCTION:
You MUST fix these issues in this retry. Pay close attention to the critique and adjust your reasoning, citations, or formatting accordingly.
=========================================
"""
    return evolved
