"""Synthetic observations must never enter working memory or consolidation."""
from datetime import datetime, timezone
from unittest.mock import AsyncMock

import pytest

pytestmark = pytest.mark.real_mongo


def test_writes_and_legacy_readers_exclude_synthetic(real_mongo, monkeypatch):
    from app.db import mongo_store, memory_repo
    from app.services.memory.store import MemoryStore
    from app.services.memory.episodic_memory import EpisodicMemoryStore
    from app.services.learning.consolidation import source_query, discover
    monkeypatch.setattr(mongo_store, '_BACKENDS', {'*': 'mongo'})
    stamp = datetime.now(timezone.utc)
    store, episodes = MemoryStore(), EpisodicMemoryStore()
    for cycle in ('cycle-observe-123', 'bench-ticket-123', 'canary_v3_123'):
        assert store.add_episodic_observation({'cycle_id': cycle}) == ''
        assert episodes.write_episode(cycle, 'FIXT', 'Synthetic only') == ''
    assert mongo_store.count_docs('episodic_observations', {}) == 0
    assert mongo_store.count_docs('episodic_memory', {}) == 0
    # Bypass the writers to represent rows created by older deployments.
    for index, cycle in enumerate(('cycle-v3-123', 'legacy-cycle', None, 'cycle-observe-123', 'bench-ticket-123')):
        common = {'id': str(index), 'ticker': 'FIXT', 'cycle_id': cycle}
        mongo_store.insert_docs('episodic_observations', [{**common,
            'created_at': stamp, 'promoted_to_memory': False, 'observation_text': 'Stored evidence.'}])
        mongo_store.insert_docs('episodic_memory', [{**common,
            'timestamp': stamp, 'summary': 'Stored evidence.', 'outcome_score': 0,
            'key_decisions': '[]', 'outcome': 'pending'}])
    expected = {'0', '1', '2'}
    assert {r['id'] for r in memory_repo.get_unpromoted_observations('FIXT')} == expected
    assert {r['id'] for r in store.get_unpromoted_observations()} == expected
    assert {r['id'] for r in episodes.retrieve('FIXT', limit=10)} == expected
    assert {r['id'] for r in mongo_store.find_docs('episodic_observations', source_query('FIXT'))} == expected
    assert discover() == {'eligible_tickers': 0, 'unpromoted': 0}  # synthetic rows cannot meet the five-row threshold
    # Normal writes still work.
    assert store.add_episodic_observation({'cycle_id': 'cycle-v3-456', 'ticker': 'LIVE',
        'source_type': 'v3_pipeline', 'observation_text': 'Production evidence.'})
    assert episodes.write_episode('cycle-v3-456', 'LIVE', 'Production evidence.')


@pytest.mark.asyncio
async def test_explicit_consolidation_input_cannot_bypass_scope(real_mongo, monkeypatch):
    from app.services.memory import consolidator
    from app.services.learning.consolidation import validate_result
    llm = AsyncMock()
    monkeypatch.setattr(consolidator, 'call_prism_agent', llm)
    quote = 'This observation was generated by a synthetic evaluation cycle.'
    source = {'id': 'synthetic', 'ticker': 'FIXT', 'cycle_id': 'cycle-observe-123',
        'created_at': datetime.now(timezone.utc), 'observation_text': quote}
    assert await consolidator.run_ticker_consolidation('FIXT', observations=[source]) == 'empty'
    llm.assert_not_called()
    with pytest.raises(ValueError, match='Missing observation'):
        validate_result({'new_or_updated_memories': [{'source_evidence': [
            {'observation_id': 'synthetic', 'quote': quote}]}]}, 'FIXT', [source], [])
