"""
charting_tools.py — LLM-driven technical analysis chart generator.

Restored from git history (commit e6e1c73). This tool:
1. Accepts a ticker + overlay list from the LLM technical analyst agent
2. Renders a Plotly HTML chart with overlays drawn on it
3. Writes a {TICKER}.json to data/charts/ for the frontend AgenticChart to poll

The AgenticChart component in the trading-client fetches:
    GET /tools-api/charts/{TICKER}.json
and displays the overlays (support zones, resistance zones, trendlines) on
the interactive ECharts candlestick chart in the ticker detail panel.
"""

import os
import json
import asyncio
import datetime
import logging

import pandas as pd
import yfinance as yf
from pydantic import BaseModel, Field

from app.tools.registry import registry

logger = logging.getLogger(__name__)

# CHART_OUTPUT_DIR env var overrides the default.
# In the lazy-tool-service container: /app/data/charts (volume-mounted).
# The default MUST resolve to the same directory as chart_router.CHARTS_DIR
# (trading-service/data/charts) — the router is the reader for these files.
_default_charts_dir = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "../../data/charts")
)
OUTPUT_DIR = os.environ.get("CHART_OUTPUT_DIR", _default_charts_dir)


class ChartingInput(BaseModel):
    ticker: str = Field(description="The stock ticker symbol (e.g. AAPL)")
    overlays: list = Field(
        default_factory=list,
        description="List of technical overlays (lines, zones) generated by the agent",
    )
    period: str = Field(
        default="6mo",
        description="Timeframe of historical data to fetch (e.g., '1mo', '3mo', '6mo', '1y')",
    )
    analysis: str = Field(
        default="",
        description="A plain-English summary of the technical analysis from the agent",
    )
    strategy_name: str = Field(
        default="",
        description="Name of the trading strategy or framework used by the agent",
    )
    confidence: str = Field(
        default="",
        description="Agent confidence level (e.g., HIGH, MEDIUM, LOW or a percentage)",
    )
    reasoning: str = Field(
        default="",
        description="Extended reasoning or chain-of-thought from the agent",
    )


def fetch_data(symbol: str, period: str = "6mo") -> pd.DataFrame:
    df = yf.Ticker(symbol).history(period=period)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    if len(df) == 0:
        raise ValueError(f"No price data found for {symbol}")
    df["EMA_20"] = df["Close"].ewm(span=20, adjust=False).mean()
    df["EMA_50"] = df["Close"].ewm(span=50, adjust=False).mean()
    if df.index.tz is not None:
        df.index = df.index.tz_localize(None)
    return df


def render_chart(df: pd.DataFrame, spec: dict, symbol: str) -> str:
    """Render an HTML Plotly chart with overlays and return the filename."""
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots

    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.03,
        subplot_titles=(f"{symbol} · Technical Analysis", "Volume"),
        row_width=[0.2, 0.7],
    )

    fig.add_trace(
        go.Candlestick(
            x=df.index,
            open=df["Open"],
            high=df["High"],
            low=df["Low"],
            close=df["Close"],
            name="Price",
        ),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scatter(x=df.index, y=df["EMA_20"], line=dict(color="orange", width=1.5), name="EMA 20"),
        row=1,
        col=1,
    )
    fig.add_trace(
        go.Scatter(x=df.index, y=df["EMA_50"], line=dict(color="purple", width=1.5), name="EMA 50"),
        row=1,
        col=1,
    )

    colors = ["green" if row["Close"] >= row["Open"] else "red" for _, row in df.iterrows()]
    fig.add_trace(go.Bar(x=df.index, y=df["Volume"], marker_color=colors, name="Volume"), row=2, col=1)

    for ov in spec.get("overlays", []):
        kind = ov.get("kind") or ov.get("type")
        if kind in ("line", "support", "resistance", "trendline"):
            x0 = ov.get("x0", df.index[0])
            x1 = ov.get("x1", df.index[-1])
            y0 = ov.get("y0")
            y1 = ov.get("y1")
            if y0 is not None and y1 is not None:
                fig.add_shape(
                    type="line",
                    x0=x0, y0=y0, x1=x1, y1=y1,
                    line=dict(color=ov.get("color", "white"), width=2, dash="dashdot"),
                    row=1, col=1,
                )
                fig.add_annotation(
                    x=x1, y=y1, text=ov.get("reasoning", ""),
                    showarrow=False, yshift=10,
                    font=dict(color=ov.get("color", "white")),
                    row=1, col=1,
                )
        elif kind in ("zone", "volume_void"):
            is_void = kind == "volume_void"
            fc = ov.get("color", "purple" if is_void else "blue")
            x0 = ov.get("x0", df.index[0])
            x1 = ov.get("x1", df.index[-1])
            y0 = ov.get("y0")
            y1 = ov.get("y1")
            if y0 is not None and y1 is not None:
                fig.add_shape(
                    type="rect",
                    x0=x0, y0=y0, x1=x1, y1=y1,
                    line=dict(color=fc, width=1 if is_void else 0, dash="dot" if is_void else "solid"),
                    fillcolor=fc,
                    opacity=0.3 if is_void else 0.2,
                    row=1, col=1,
                )
                fig.add_annotation(
                    x=x0, y=y1, text=ov.get("reasoning", ""),
                    showarrow=False, yshift=10,
                    font=dict(color=ov.get("color", "white")),
                    row=1, col=1,
                )

    fig.update_layout(
        title=f"{symbol} · Technical Agent Overlays",
        template="plotly_dark",
        xaxis_rangeslider_visible=False,
        height=800,
    )

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    filename = f"{symbol}_{int(datetime.datetime.now().timestamp())}.html"
    out = os.path.join(OUTPUT_DIR, filename)
    fig.write_html(out)
    return filename


_KNOWN_OVERLAY_TYPES = {"support", "resistance", "trendline", "line", "zone", "volume_void"}

# Aliases the LLM has been observed to emit → canonical type
_OVERLAY_TYPE_ALIASES = {
    "horizontal_line": "zone",
    "support_zone": "support",
    "resistance_zone": "resistance",
    "supply_zone": "resistance",
    "demand_zone": "support",
    "sma_200": "zone",
    "sma_50": "zone",
    "sma_20": "zone",
}


def _to_float(val):
    try:
        f = float(val)
        return f if f == f else None  # reject NaN
    except (TypeError, ValueError):
        return None


def normalize_overlays(overlays: list) -> list:
    """Coerce LLM-authored overlays into the schema AgenticChart.jsx renders.

    Agents routinely emit string prices ("81"), alias types (horizontal_line,
    support_zone), a bare `price` field, or a nested `price_range` — all of
    which either crash or silently vanish in the frontend. Normalize to:
    {type, y0: float, y1: float, x0?, x1?, color?, reasoning}. Overlays with
    no usable price coordinates are dropped.
    """
    normalized = []
    for ov in overlays or []:
        if not isinstance(ov, dict):
            continue
        raw_type = ov.get("type") or ov.get("kind") or ""
        if not isinstance(raw_type, str):
            raw_type = str(raw_type)
        ov_type = raw_type.lower().strip()
        label_hint = str(ov.get("label") or "").lower()
        if ov_type not in _KNOWN_OVERLAY_TYPES:
            # Map aliases; use the label to disambiguate generic lines
            if "support" in ov_type or "support" in label_hint:
                ov_type = "support"
            elif "resist" in ov_type or "resist" in label_hint:
                ov_type = "resistance"
            else:
                ov_type = _OVERLAY_TYPE_ALIASES.get(ov_type, "zone")

        price_range = ov.get("price_range") if isinstance(ov.get("price_range"), dict) else {}
        y0 = _to_float(ov.get("y0", price_range.get("y0", ov.get("price"))))
        y1 = _to_float(ov.get("y1", price_range.get("y1", ov.get("price"))))
        if y0 is None and y1 is None:
            logger.warning("[charting_tools] Dropping overlay with no usable prices: %s", ov)
            continue
        y0 = y0 if y0 is not None else y1
        y1 = y1 if y1 is not None else y0

        clean = {
            "type": ov_type,
            "y0": y0,
            "y1": y1,
            "reasoning": str(ov.get("reasoning") or ov.get("label") or ""),
        }
        for key in ("x0", "x1"):
            if ov.get(key):
                clean[key] = str(ov[key])
        if ov.get("color"):
            clean["color"] = str(ov["color"])
        normalized.append(clean)
    return normalized


@registry.register(
    name="save_trading_chart",
    description=(
        "Save an AI-annotated technical analysis chart for a ticker. "
        "Call this after your technical analysis is complete. Pass your overlays (support/resistance zones, "
        "trendlines) as JSON, along with a plain-English analysis summary. "
        "The chart is written to the shared charts directory and immediately displayed "
        "in the trading client's ticker detail panel under 'AI Analysis Overlays'."
    ),
    parameters={
        "type": "object",
        "properties": {
            "ticker": {"type": "string", "description": "The stock ticker symbol (e.g. AAPL)"},
            "overlays": {
                "type": "array",
                "description": (
                    "List of technical overlay objects. Each object must have: "
                    "type (support|resistance|trendline|zone|volume_void), "
                    "y0 (float, lower price), y1 (float, upper price), "
                    "x0 (optional date string, start), x1 (optional date string, end), "
                    "color (optional: green|red|blue|purple|yellow), "
                    "reasoning (string label shown on the chart)"
                ),
            },
            "period": {
                "type": "string",
                "description": "Timeframe of historical data (e.g., '1mo', '3mo', '6mo', '1y'). Default: '6mo'",
            },
            "analysis": {
                "type": "string",
                "description": "Plain-English summary of the technical analysis shown below the chart",
            },
            "strategy_name": {
                "type": "string",
                "description": "Name of the strategy or framework used (e.g., 'Breakout + Volume Confirmation')",
            },
            "confidence": {
                "type": "string",
                "description": "Confidence level (e.g., HIGH, MEDIUM, LOW)",
            },
            "reasoning": {
                "type": "string",
                "description": "Extended step-by-step reasoning chain (shown as collapsible 'Show Reasoning')",
            },
        },
        "required": ["ticker", "overlays"],
    },
    tier=1,
    source="data_sink",
    input_model=ChartingInput,
)
async def save_trading_chart(
    ticker: str,
    overlays: list = None,
    period: str = "6mo",
    analysis: str = "",
    strategy_name: str = "",
    confidence: str = "",
    reasoning: str = "",
) -> str:
    """
    Takes LLM-generated overlay data and saves the chart + JSON for the frontend.

    The JSON format consumed by AgenticChart.jsx:
        {
          "latest_analysis": {
            "overlays": [...],
            "analysis": "...",
            "strategy_name": "...",
            "confidence": "...",
            "reasoning": "..."
          }
        }
    """
    if overlays is None:
        overlays = []
    if isinstance(overlays, str):
        # Some agents pass overlays as a JSON string
        try:
            overlays = json.loads(overlays)
        except Exception:
            overlays = []
    overlays = normalize_overlays(overlays)

    symbol = ticker.upper().strip()
    logger.info("[charting_tools] Generating chart for %s with %d overlays", symbol, len(overlays))

    try:
        df = await asyncio.to_thread(fetch_data, symbol, period)
    except Exception as e:
        logger.error("[charting_tools] Failed to fetch price data for %s: %s", symbol, e)
        return f"Failed to fetch price data for {symbol}: {e}"

    spec = {"overlays": overlays}

    # The frontend (AgenticChart.jsx) only consumes the JSON below — the Plotly
    # HTML is a standalone artifact. Render it best-effort AFTER the JSON is
    # safely on disk so a Plotly failure can never block the overlays.
    filename = ""

    # Save the JSON payload for the AgenticChart frontend component
    try:
        df_json = df.reset_index()
        df_json["Date"] = df_json["Date"].dt.strftime("%Y-%m-%d")

        latest_analysis = {
            "overlays": overlays,
            "analysis": analysis,
            "strategy_name": strategy_name,
            "confidence": confidence,
            "reasoning": reasoning,
            "filename": filename,
            "status": "success",
        }

        json_data = {
            "symbol": symbol,
            "period": period,
            "timestamp": int(datetime.datetime.now().timestamp()),
            "latest_analysis": latest_analysis,
        }

        os.makedirs(OUTPUT_DIR, exist_ok=True)
        json_path = os.path.join(OUTPUT_DIR, f"{symbol}.json")
        with open(json_path, "w") as f:
            json.dump(json_data, f)

        logger.info("[charting_tools] Saved chart JSON for %s → %s", symbol, json_path)
    except Exception as e:
        logger.error("[charting_tools] Failed to save JSON for %s: %s", symbol, e)
        return f"JSON save failed for {symbol}: {e}"

    try:
        filename = await asyncio.to_thread(render_chart, df, spec, symbol)
    except Exception as e:
        # Non-fatal: the overlays the frontend needs are already saved above.
        logger.warning("[charting_tools] Plotly render failed for %s (JSON already saved): %s", symbol, e)

    if filename:
        try:
            json_data["latest_analysis"]["filename"] = filename
            with open(json_path, "w") as f:
                json.dump(json_data, f)
        except Exception:
            pass

    return (
        f"Successfully generated technical analysis chart for {symbol}.\n\n"
        f"The chart overlays are now live in the trading client ticker detail panel.\n"
        f"Overlays saved: {len(overlays)}"
    )
