"""
Tool Registry wrapper for trading-service.
Imports the generic registry from lazycat-sdk and loads remote schemas.
"""
import json
import os
import tempfile
import logging
from lazycat.tool_registry import ToolRegistry, ToolMeta, PermissionLevel, registry

logger = logging.getLogger(__name__)

# Load schemas from the local file generated by lazy-tool-service — SCOPED to
# this app. The flat catalog is ecosystem-wide (html-notes widgets, treesearch
# cannabis tools, …); loading all of it bloated the schema surface and meant a
# whitelist bug could hand a trading agent a foreign tool. The generator
# stamps owner_app on every tool; keep trading's own plus any unstamped
# (hand-added) entries so a missing stamp degrades open, not silently closed.
_OWNER_SCOPE = {"trading"}

schemas_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "tool_schemas.json")


def _load_scoped_schemas(path: str) -> None:
    try:
        with open(path, "r", encoding="utf-8") as f:
            all_tools = json.load(f)
        if not isinstance(all_tools, list):
            raise ValueError(f"expected a list, got {type(all_tools).__name__}")
        scoped = [
            t for t in all_tools
            if t.get("owner_app") is None or t.get("owner_app") in _OWNER_SCOPE
        ]
        dropped = sorted(
            t["name"] for t in all_tools
            if t not in scoped and t.get("name")
        )
        scoped_path = os.path.join(tempfile.gettempdir(), "tool_schemas.trading.json")
        with open(scoped_path, "w", encoding="utf-8") as f:
            json.dump(scoped, f)
        registry.load_from_json(scoped_path)
        logger.info(
            "[ToolRegistry] Scoped catalog to owner_app=%s: %d/%d tools loaded "
            "(dropped foreign: %s%s)",
            sorted(_OWNER_SCOPE), len(scoped), len(all_tools),
            ", ".join(dropped[:8]), " …" if len(dropped) > 8 else "",
        )
    except Exception as e:
        # Never let scoping break boot — fall back to the full catalog.
        logger.error("[ToolRegistry] Scoped load failed (%s) — loading full catalog", e)
        registry.load_from_json(path)


_load_scoped_schemas(schemas_path)

def _db_telemetry_callback(
    tool_name: str,
    agent_name: str | None,
    success: bool,
    execution_ms: int,
    error_message: str | None,
) -> None:
    """Log a tool usage event to PostgreSQL (fire-and-forget).

    Attribution comes from the tool CONTEXT when the caller does not supply it
    (2026-07-29). Measured over 7 days: all 2,066 rows carried
    agent_name='unknown', and ticker/cycle_id were not written at all — the
    INSERT simply omitted both columns. So "which agent researches, and how
    much?" was unanswerable, which is the question you have to answer before
    you can rebalance research spend.

    The SDK invokes this callback with five positional args and drops ticker
    and cycle_id on the way (lazycat/tool_registry.py:848), even though its own
    _log_usage accepts them — so they cannot arrive through the signature and
    must be read from the contextvars the router populates.
    """
    try:
        from datetime import datetime, timezone
        from app.db.connection import get_db
        from app.tools.tool_context import (
            current_agent_name, current_cycle_id, current_ticker,
        )

        # Passed value wins; context is the fallback. current_agent_name()
        # already resolves the AGENT_NAME env var and returns "unknown" last.
        agent_name = agent_name or current_agent_name()
        try:
            cycle_id = current_cycle_id()
        except Exception:
            cycle_id = None
        # current_cycle_id() returns the literal "default_cycle" when it cannot
        # resolve one. That sentinel is fine for tools that need *a* key, but
        # storing it here would invent a cycle that never ran and silently pool
        # unrelated calls under one id. NULL is the honest answer.
        if cycle_id == "default_cycle":
            cycle_id = None
        ticker = current_ticker()

        with get_db() as db:
            db.execute(
                "INSERT INTO tool_usage_stats "
                "(tool_name, agent_name, ticker, cycle_id, success, execution_ms, "
                " error_message, service_source, called_at) "
                "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
                [
                    tool_name,
                    agent_name,
                    ticker,
                    cycle_id,
                    success,
                    execution_ms,
                    error_message,
                    "lazy-tool-service",
                    datetime.now(timezone.utc),
                ],
            )
    except Exception as e:
        logger.debug(f"[ToolRegistry] Usage log failed (non-fatal): {e}")

registry.set_telemetry_callback(_db_telemetry_callback)

__all__ = ["ToolRegistry", "ToolMeta", "PermissionLevel", "registry"]
