"""Every Postgres-bound file outside app/ carries a decision.

THE HALF THE WRITER GUARD DOES NOT COVER
----------------------------------------
`test_no_pg_writers_for_trading_data.py` catches a script that WRITES to the
frozen archive. It was built on 2026-08-30, it has real controls, and it works.

Nothing catches a script that READS from it, and the reads are the larger
population — 67 files against 18 writers. A write to the wrong store loses data
and can be re-run. A read from the wrong store loses a DECISION and looks like a
report: `scripts/shadow_report.py` runs clean today and prints rows dated
2026-07-29 citing `tournament_result`, a subsystem deleted on 08-28. It does not
say the data is a month old, because nothing knows to say so.

Porting 40 scripts is a queue, not a gate. What a gate CAN do is make sure the
queue is complete and stays complete: every PG-bound file is named, every name
carries a disposition somebody chose, and a new one cannot appear unnoticed.

WHY THE JSON RATHER THAN A SET IN THIS FILE
-------------------------------------------
The disposition is a human decision with a reason attached, and the reasons are
the durable part — `why` is why the next reader does not re-litigate whether
`purge_bad_data.py` should be ported (it operates ON the archive by definition).
A dict of 67 justified entries in a test module is a document pretending to be
code. It lives in docs/migration/pg_script_inventory.json and is regenerated by
`python scripts/pg_script_inventory.py --write`.
"""
from __future__ import annotations

import json
import pathlib

import pytest

from scripts.pg_script_inventory import DISPOSITIONS, classify, merge, scan

REPO = pathlib.Path(__file__).resolve().parents[2]
INVENTORY = REPO / "docs" / "migration" / "pg_script_inventory.json"


@pytest.fixture(scope="module")
def merged():
    stored = json.loads(INVENTORY.read_text())
    return merge(scan(), stored)


#: Files that read Postgres ON PURPOSE and are not going anywhere: the archive
#: pool, the backfill, the seeder and the parity instruments. They are what the
#: retirement is measured WITH, so they outlive every port by construction.
#: Naming them is a non-vacuity floor that cannot decay as the work succeeds —
#: unlike a headcount, which does.
PERMANENT_ARCHIVE_READERS = frozenset({
    "scripts/migration/pg_connection.py",
    "scripts/pg_to_mongo_backfill.py",
    "scripts/quality_census.py",
    "scripts/pg_quiescence.py",
    "scripts/migrate_all.py",
})


def test_the_scan_is_not_vacuous(merged):
    """A scan that looked at nothing satisfies every assertion below.

    This is the same failure the soak-instrument guard names: "a scan that finds
    nothing because it LOOKED at nothing passes just as happily".

    THE FLOOR IS NAMED, NOT COUNTED, and the reason is written into the count's
    own obituary. `len(rows) >= 40` said "it was 67 on 2026-08-30 and shrinks by
    ports and deletions, not by a factor of two overnight" — and then 35 files
    were ported in one session and it fell to 33, correctly. A population floor
    on a population the work exists to shrink goes red for success and gets
    lowered until it means nothing; this is the third such floor in this repo to
    do it (see COMBINED_READ_FLOOR in test_price_history_one_vendor_guard.py and
    SCRIPTS_RATCHET in test_soak_instruments_read_mongo.py).

    So the check is now that the scanner still finds the files that CANNOT
    leave. If those go missing the scanner is broken; if the count merely falls,
    the migration worked.
    """
    rows, _new, _gone = merged
    seen = {r["path"] for r in rows}
    missing = sorted(PERMANENT_ARCHIVE_READERS - seen)
    assert not missing, (
        f"the scanner cannot see {missing} — these read Postgres deliberately "
        "and permanently, so their absence is the SCANNER failing, not the "
        "shelf emptying. (Delete one from PERMANENT_ARCHIVE_READERS only when "
        "the file itself is genuinely gone, and say where it went.)"
    )
    # A small numeric floor is kept underneath, as a second signal: the named
    # five plus the rest of the retained archive tooling. Lower it only for a
    # DELETION, and record which file went.
    assert len(rows) >= 25, (
        f"only {len(rows)} Postgres-bound files found. The five named above are "
        "present, so the scanner works — but the retained archive tooling alone "
        "is more than this, so something has been deleted without a note."
    )


def test_every_postgres_bound_file_carries_a_disposition(merged):
    rows, new, _gone = merged
    assert not new, (
        "these can reach Postgres and nobody has said what should happen to "
        "them. Classify each in docs/migration/pg_script_inventory.json as "
        "mongo | archive-only | parity-only | delete, with a reason, then "
        f"re-run `python scripts/pg_script_inventory.py --write`:\n  "
        + "\n  ".join(new)
    )


def test_the_inventory_has_no_rows_for_files_that_are_gone(merged):
    """The other direction, and the one that rots quietly.

    An entry that outlives its file is an allowlist that has stopped guarding
    anything — the same finding as the treesearch foreign-owner list, which
    named `glass_votes` (a table that never existed) while missing two live
    ones, and kept the count at 14 either way.
    """
    _rows, _new, gone = merged
    assert not gone, (
        "the inventory names files that no longer exist; drop the rows: "
        f"{gone}"
    )


def test_every_disposition_is_one_of_the_four(merged):
    rows, _new, _gone = merged
    bad = {r["path"]: r["disposition"] for r in rows
           if r["disposition"] not in DISPOSITIONS}
    assert not bad, bad


def test_every_row_that_is_not_being_ported_says_why(merged):
    """`archive-only` and `parity-only` are the two answers that keep a file on
    Postgres forever. Neither is free: each one is a path by which the frozen
    store can still answer a question. They pay for themselves with a sentence."""
    rows, _new, _gone = merged
    silent = [r["path"] for r in rows
              if r["disposition"] in ("archive-only", "parity-only")
              and not r.get("why")]
    assert not silent, (
        "kept on Postgres with no reason recorded: " + ", ".join(silent)
    )


def test_the_stored_file_matches_a_fresh_scan(merged):
    """The JSON is committed, so it can go stale against the tree it describes."""
    rows, _new, _gone = merged
    stored = json.loads(INVENTORY.read_text())["rows"]
    assert [r["path"] for r in stored] == [r["path"] for r in rows], (
        "docs/migration/pg_script_inventory.json is out of date — re-run "
        "`python scripts/pg_script_inventory.py --write`"
    )


def test_the_connectability_split_is_the_one_that_matters(merged):
    """`can_connect` is the field to triage by, so it must actually discriminate.

    A file reaching the DSN only through `settings.DATABASE_URL` raises
    AttributeError today and is LOUD. One reading the environment still works,
    and answers from 2026-08-19. If every row came back the same way, the field
    would be decoration.
    """
    rows, _new, _gone = merged
    yes = [r for r in rows if r["can_connect"]]
    no = [r for r in rows if not r["can_connect"]]
    assert yes and no, (
        f"can_connect is not discriminating: {len(yes)} yes / {len(no)} no"
    )


def test_the_classifier_sees_each_mechanism(tmp_path):
    """NEGATIVE CONTROL, per mechanism.

    Everything above passes on a classifier that returns None for every file.
    Each shape below is one this audit actually found in the tree, including the
    two the previous count missed: a hardcoded DSN default, and the shared
    `pg_url()` helper that parses `.env` off disk when the env var is unset.
    """
    cases = {
        "a.py": ("import psycopg\n"
                 "c = psycopg.connect(os.getenv('DATABASE_URL'))\n", True),
        "b.py": ("import psycopg2\n"
                 "c = psycopg2.connect(os.environ.get('DATABASE_URL',"
                 " 'postgresql://trader:pw@10.0.0.16:5433/trading_bot'))\n", True),
        "c.py": ("import psycopg\n"
                 "from scripts.quality_census import pg_url\n"
                 "c = psycopg.connect(pg_url())\n", True),
        "d.py": ("from scripts.migration.pg_connection import get_db\n"
                 "with get_db() as db:\n    pass\n", False),
    }
    for name, (src, expect_connect) in cases.items():
        path = tmp_path / name
        path.write_text(src)
        row = classify(path)
        assert row is not None, f"{name}: the classifier missed a real coupling"
        assert row["can_connect"] is expect_connect, (name, row["mechanisms"])


def test_prose_about_postgres_is_not_a_coupling(tmp_path):
    """The other direction. Half of scripts/ EXPLAINS what the migration
    changed; a guard that fires on its own explanation is one people silence."""
    path = tmp_path / "ok.py"
    path.write_text(
        '"""We used to psycopg.connect(os.getenv("DATABASE_URL")) here.\n\n'
        'The DSN was postgresql://trader@10.0.0.16:5433/trading_bot.\n"""\n'
        "# import psycopg  -- what this replaced\n"
        "x = 1\n"
    )
    assert classify(path) is None
