"""Statistics inside the equation sandbox (2026-07-29).

scipy is not importable in the sandbox, so an equation had `np` and `pd` and no
way to compute a normal CDF, a t-stat or a confidence interval. The measured
consequence was not that agents stopped computing — it was that they computed
elsewhere. Over 30 days:

    run_equation ...... 18 calls   (v3_quant_analyst)
    execute_python .... 27 calls, 27 successful, FOUR agents
                        (quant 18, board 4, regime 4, synthesizer 1)

So the demand was already expressed through a generic escape hatch. These tests
pin the two halves that have to ship together, because either alone is useless:

  1. the helpers are actually IN the sandbox globals, and actually run there
  2. the tool DESCRIPTIONS name them

Half 2 is not documentation. `app/v3/agents/quant_analyst.py` records the
measured rule twice over: a tool the prompt does not name is a tool that gets
zero calls, and a tool the prompt still names after its replacement keeps
burning turns. A helper injected silently is a helper no model will ever reach
for — the "shipped the mechanism, not the capability" failure.
"""

import numpy as np
import pytest

from app.cognition.debate.equation_library import (
    SAFE_GLOBALS,
    _STAT_HELPERS,
    execute_equation,
)
from app.tools import quant_tools  # noqa: F401  (registers the tools)


EXPECTED = {
    "newey_west_tstat",
    "stationary_bootstrap_ci",
    "probabilistic_sharpe_ratio",
    "deflated_sharpe_ratio",
    "min_track_record_length",
    "is_oos_degradation",
    "full_gate",
    "suggest_lag",
    "norm_cdf",
}


# ── half 1: the helpers are present and usable ───────────────────────

def test_every_expected_helper_is_in_the_sandbox():
    missing = EXPECTED - set(SAFE_GLOBALS)
    assert not missing, f"not injected into SAFE_GLOBALS: {sorted(missing)}"


def test_helpers_are_callable_not_just_present():
    for name in EXPECTED:
        assert callable(SAFE_GLOBALS[name]), f"{name} is not callable"


def test_scipy_is_still_not_importable():
    """The helpers exist precisely BECAUSE scipy is unavailable. If scipy ever
    becomes importable here that is a security-surface change, not a win."""
    from app.cognition.debate.equation_library import _ALLOWED_IMPORT_ROOTS

    assert "scipy" not in _ALLOWED_IMPORT_ROOTS


def test_no_new_dependency_was_added():
    """stat_gates must stay scipy-free, or injecting it drags scipy in."""
    import app.quant.stat_gates as sg
    import inspect

    src = inspect.getsource(sg)
    assert "import scipy" not in src and "from scipy" not in src


# ── half 2: the descriptions name them ───────────────────────────────

def _live_schema_text(tool_name: str) -> str:
    """The description as the MODEL sees it — from the loaded registry.

    NOT from `inspect.getsource(quant_tools)`. The Python `description=` in the
    @registry.register decorator is NOT what reaches the model: `tool_schemas.json`
    (a gitignored build artifact, generated by scripts/build_tool_schemas.py from
    lazy-agent-service/tool_schemas/<owner>/<domain>.json) is loaded over it by
    app/tools/registry.py:_load_scoped_schemas. Verified 2026-07-29 by editing the
    Python literal and observing the live schema unchanged.

    Grepping the Python source therefore produces a test that CANNOT FAIL while
    the model sees nothing — which is how a capability ships inert.
    """
    from lazycat.tool_registry import registry

    schemas = registry.get_schemas_by_names([tool_name]) or []
    if not schemas:
        pytest.skip(
            "tool_schemas.json not present in this checkout (it is gitignored, "
            "so worktrees lack it) — cannot assert on the live description"
        )
    fn = schemas[0].get("function", schemas[0])
    params = (fn.get("parameters") or {}).get("properties", {})
    return " ".join([
        fn.get("description") or "",
        *(str(p.get("description") or "") for p in params.values()),
    ])


@pytest.mark.parametrize("tool", ["run_equation", "save_equation"])
def test_live_schema_names_every_injected_helper(tool):
    """A helper the LIVE schema omits is a helper with zero calls.

    This is the half that makes the injection reachable. `quant_analyst.py`
    records the rule twice from measurement: a tool the prompt/schema does not
    name gets zero calls.
    """
    text = _live_schema_text(tool)
    missing = [h for h in EXPECTED if h not in text]
    assert not missing, (
        f"{tool}'s LIVE schema does not mention {missing}. Fix the SOURCE — "
        f"lazy-agent-service/tool_schemas/trading/general.json — then re-run "
        f"scripts/build_tool_schemas.py. Editing the Python description= is "
        f"cosmetic; the JSON is loaded over it."
    )


def test_live_schema_says_scipy_is_unavailable():
    text = _live_schema_text("run_equation")
    assert "scipy" in text.lower(), (
        "the schema must say scipy is unimportable, or equations keep opening "
        "with `import scipy` and dying on the first line"
    )


# ── the helpers actually work through the real executor ──────────────

@pytest.fixture
def _stub_prices(monkeypatch):
    """Stub the price load so the exec path is tested without a DB.

    A test that skips proves nothing, and this is the one assertion that
    matters: presence in SAFE_GLOBALS is not proof the sandbox can REACH a
    name — execute_equation builds its own `dict(SAFE_GLOBALS)` and could
    shadow or drop entries.
    """
    import pandas as pd
    from app.trading import quant_edge_verifier

    df = pd.DataFrame({
        "close": np.linspace(100.0, 120.0, 200),
        "high": np.linspace(101.0, 121.0, 200),
        "low": np.linspace(99.0, 119.0, 200),
        "volume": np.full(200, 1_000_000.0),
    })
    monkeypatch.setattr(quant_edge_verifier, "load_historical_data",
                        lambda *a, **kw: df)
    return df


def test_a_real_equation_can_use_the_helpers(_stub_prices):
    code = (
        "r = np.array([0.004, -0.002, 0.006, 0.001, -0.003] * 40)\n"
        "g = full_gate(r)\n"
        "t = newey_west_tstat(r)\n"
        "n = norm_cdf(0.0)\n"
        "result = {'gate_keys': sorted(g.keys()), "
        "'tstat_keys': sorted(t.keys()), 'ncdf': n}"
    )
    out = execute_equation(code=code, ticker="AAPL", parameters={})
    assert out.get("status") == "ok", out
    assert out["result"]["gate_keys"], out
    assert out["result"]["tstat_keys"], out
    assert abs(out["result"]["ncdf"] - 0.5) < 1e-6, out


def test_helper_names_resolve_inside_exec_not_just_in_the_dict(_stub_prices):
    """The failure this guards: a NameError at exec time despite the name being
    in SAFE_GLOBALS."""
    for helper in sorted(EXPECTED):
        out = execute_equation(
            code=f"result = {{'ok': callable({helper})}}",
            ticker="AAPL", parameters={},
        )
        assert out.get("status") == "ok", f"{helper} unreachable in sandbox: {out}"
        assert out["result"]["ok"] is True, helper


def test_scipy_import_still_fails_inside_the_sandbox(_stub_prices):
    out = execute_equation(code="import scipy\nresult = 1",
                           ticker="AAPL", parameters={})
    assert "error" in out, "scipy must remain unimportable in the sandbox"
    assert "not allowed" in out["error"].lower() or "import" in out["error"].lower()


def test_deflated_sharpe_penalises_more_trials():
    """The reason DSR is here: an equation library IS multiple testing."""
    r = np.array([0.004, -0.002, 0.006, 0.001, -0.003] * 40)
    few = SAFE_GLOBALS["deflated_sharpe_ratio"](r, n_trials=1)
    many = SAFE_GLOBALS["deflated_sharpe_ratio"](r, n_trials=200)

    def _p(d):
        for k in ("dsr", "deflated_sharpe", "p_value", "psr"):
            if k in d and isinstance(d[k], (int, float)):
                return float(d[k])
        pytest.skip(f"unexpected DSR shape: {sorted(d)}")

    assert _p(many) <= _p(few), "more trials must not look MORE significant"


def test_norm_cdf_is_a_real_cdf():
    f = SAFE_GLOBALS["norm_cdf"]
    assert abs(f(0.0) - 0.5) < 1e-6
    assert f(-3.0) < 0.005 < 0.995 < f(3.0)
    assert f(-1.0) < f(0.0) < f(1.0)
